### ISSUE TITLE
Create ZIP doesn't add file extension

### ISSUE THREAD

**Issue by abotkin-cpi** [bitrise-steplib/steps-create-zip#7]
In using the step to ZIP an XCResult file from Xcode Test step for saving to the deploy directory, it appears that the step doesn't add the ".zip" extension onto directories with an extension already (like "Test.xcresult") & so when a user downloads the file, they have to know to add the ".zip" extension as macOS will use the provided file extension of ".xcresult" & think the ZIP is still an xcresult & fail to parse.

It would be nice if there were an option to specify that I want the ZIP to add the file extension on.

**Comment by bitce** [comment]
Hi there!

Thanks for pointing this issue out, can you please paste here a build that produced a file containing this issue?

**Comment by abotkin-cpi** [comment]
This build should be publicly viewable - let me know if not: https://app.bitrise.io/build/860c252b7d1ff657#?tab=artifacts

In here, the Test.xcresult when downloaded on macOS is coming down without a ".zip" extension and so it looks like it's an xcresult that can be opened by Xcode, but can't until the user unzips the file. User ends up having to add the ".zip" name themselves either in a separate script step or manually.

The bitrise.yml on the workflow looks like this:

```
    - create-zip@0:
        title: Attach xcresult as ZIP to Deploy
        inputs:
        - destination: "$BITRISE_DEPLOY_DIR"
        - source_path: "$BITRISE_XCRESULT_PATH"
        is_always_run: true
    - deploy-to-bitrise-io@1.9: {}
```
